project:
  type: site
  output-dir: docs

site:
  title: "MPX in North Carolina"
  open-graph: true
  twitter-card: true
  reader-mode: true
  page-footer: 
    left:
      - text: "Learn More About the Department"
        href: "https://www.wakehealth.edu/Specialty/i/Infectious-Diseases"
    center: 
      - text: "Disclaimer"
        href: disclaimer.qmd
  navbar:
    type: dark
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: us.qmd
        

format:
  html:
    theme: flatly
    css: styles.css
    toc: true