project:
  type: site
  output-dir: docs

site:
  title: "MPX in North Carolina"
  site-url: "https://mpx.wakeforestid.com"
  favicon: assets/wfsom.ico
  open-graph: true
  twitter-card: true
  reader-mode: true
  page-footer: 
    left:
      - text: "Learn More About the Department"
        href: "https://www.wakehealth.edu/Specialty/i/Infectious-Diseases"
    center: 
      - text: "Disclaimer"
        href: disclaimer.qmd
  navbar:
    type: dark
    background: primary
    title: false
    logo: assets/awfbh-header-logo-white-invert.png
    left:
      - href: index.qmd
        text: Home
      - href: us.qmd
      - href: vaccines.qmd
      - href: "https://wakeforestid.com"
        text: Main
        

format:
  html:
    toct: true
    code-copy: true
    code-overflow: wrap
    theme: [cosmo, theme.scss]
    css: styles.css
    after-body: "assets/"