---
title: "MPX Tracker for North Carolina"
execute:
  warning: false
  echo : false
  error: false
---

Cases updated daily by NCDHHS Monday through Friday.

```{r}
#| echo: false
library(data.table)
library(ggplot2)

dat <- fread(here::here("data", "mpx.csv"))

dat$clean_date <- with(dat, as.Date(stringr::str_extract(ping_time, "\\d{4}-\\d{2}-\\d{2}")))

dat$date_n <- as.numeric(dat$clean_date)

last_available <- format(max(dat$clean_date), "%d %B, %Y")

fit <- glm(cases ~ date_n, data = dat, family = quasipoisson())

med_est <-  -log(1/2)/coef(fit)[2]

med_se <- -log(1/2)/ confint(fit,parm = "date_n")

doubling_phrase <- sprintf("%s (95%% CI, %s-%s)",
                          round(med_est,1), round(med_se[2],1),
                           round(med_se[1],1))

```

These data are current as of `r last_available`.
Current case incidence suggests a doubling time of `r doubling_phrase` days.

```{r}
ggplot(dat, aes(x = clean_date, cases))+
  geom_point()+
  theme_bw()+
  scale_y_continuous(limits = c(0,NA), name = "Cumulative Confirmed MPX Cases")+
  scale_x_date(name = "Date")+
  labs(
    title = "Confirmed Monkeypox (MPX) Cases in North Carolina",
    caption = "Updated Monday - Friday\nData: NCDHHS"
  )
```

## Data Source

These data are pulled each weekday from the [North Carolina Department of Health's Monkeypox webpage](https://epi.dph.ncdhhs.gov/cd/diseases/monkeypox.html).
